---
- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Apache restart
  service:
    name: httpd
    state: started
    enabled: true

- name: copying file
  copy: src=devops.png dest=/var/www/html

- name: Generating templates
  template:
    src: index.html.j2
    dest:  /var/www/html/index.html
  notify:  Restart Apache
      
